version: 0.2

env:
  variables:
    BUCKET_NAME: "docs-o3.network"
    DISTRIBUTION_ID: "E11QX884F3B4SX"
phases:
  install:
    runtime-versions:
        nodejs: 10
    commands:
      - npm install -g yarn
  pre_build:
    commands:
      - echo pre build config
      - cd website
      - yarn install
  build:
    commands:
      - echo build config
      - yarn build
      - ls build
  post_build:
    commands:
      - cd build/o3-docs
      - aws s3 sync . "s3://${BUCKET_NAME}" --delete
      - aws cloudfront create-invalidation --distribution-id "${DISTRIBUTION_ID}" --paths "/*"
      - echo Build completed on `date`
